name: Feature Branch Validator
on:
  pull_request:
    branches: [ "main" ]
jobs:
  validate-source-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the source is a feature branch
        uses: actions/github-script@v6
        with:
          script: |
            const sourceBranchName = context.payload.pull_request.head.ref;
            if (!sourceBranchName.startsWith('feature/')) {
              core.setFailed('The source branch must starts with "feature/"');
            }
