name: Cross Check Verifier
on:
  pull_request_review:
jobs:
  add-dev-cross-check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is ready for the DCC
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const pull_number = context.payload.pull_request.number;
            const reviews = rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
            });
            console.log(reviews);
