name: Cross Check Verifier
on:
  pull_request_review:
jobs:
  add-dev-cross-check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is ready for the DCC
        uses: actions/github-script@v6
        with:
          script: |
            const MIN_APPROVES = 1;
            const DCC_LABEL = 'DCC';
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const { number: pull_number, labels } = context.payload.pull_request;
            const response = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
              per_page: 100,
            });
            const reviews = response.data ?? [];
            const recentReviews = Array.from(reviews.filter(({state}) =>  ['APPROVED', 'CHANGES_REQUESTED'].includes(state)).reduceRight((reviews, {state, user: {login}}) => {
            if (!reviews.has(login)) {
              reviews.set(login, state)
            }
            return reviews;
            }, new Map()).values());
            const isApproved = recentReviews.every(review => review === 'APPROVED') && recentReviews.length >= MIN_APPROVES;
            const hasDCCLabel = labels.map(({ name }) => name).includes(DCC_LABEL);
            if(isApproved && !hasDCCLabel) {
              await github.rest.issues.addLabels({owner, repo, issue_number: pull_number, labels: [DCC_LABEL] });
            }
            if(!isApproved && hasDCCLabel) {
              await github.rest.issues.removeLabel({owner, repo, issue_number: pull_number, name: DCC_LABEL });
            }
