
name: Ready State Validator
on:
  pull_request:
    types: [opened, assigned, unassigned, labeled, unlabeled]
jobs:
  validate-ready-state:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ready state conditions are met
        uses: actions/github-script@v6
        with:
          script: |
            const READY_LABEL = 'Ready';
            const { assignees, labels } = context.payload.pull_request;
            if (!assignees.length || !labels.map(({ name }) => name).includes(READY_LABEL)) {
              core.setFailed('PR is not ready');
            }
