
name: Ready State Validator
on:
  pull_request:
jobs:
  validate-ready-state:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ready state conditions are met
        uses: actions/github-script@v6
        with:
          script: |
            const READY_LABEL = 'Ready';
            const { assignee, labels } = context.payload.pull_request;
            if (!assignee && labels.map(({ name }) => name).includes(READY_LABEL)) {
              core.setFailed('PR is not ready');
            }
