name: Deploy on Release

on:
    release:
        types: [released]
jobs:
    trigger-jenkins-prod-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Dump env
          run: env | sort
        - name: Dump GitHub context
          env:
           GITHUB_TAG: ${{ github.event.release.tag_name }}
          run: echo "$GITHUB_TAG"
        - name: Check if the PR is ready for the DCC
          uses: actions/github-script@v6
          with:
            script: |
              console.log(context.payload.release.tag_name)
              console.log(context.payload)
